version: '3.7'

networks:
  net-driver:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.3.0/24

services:
  payment-api:
    build: .
    env_file: .env
    environment:
      DB_HOST: postgres
    ports:
      - "3000"
    links:
      - "postgres"
    depends_on:
      - postgres
    networks:
      net-driver:
        ipv4_address: 172.32.3.2 
  postgres:
    image: postgres
    environment:
     POSTGRES_DB: ${DB_NAME}
     POSTGRES_USER: ${DB_USER}
     POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432"
    networks:
      net-driver:
        ipv4_address: 172.32.3.3